### ISSUE TITLE
Missing some headers

### ISSUE THREAD

**Issue by patrickpoirier51** [jureviciusr/particle-match#2]
Hi,

I build on UBUNTU 20 with OpenCV version: 3.4.14
and I had to include these headers

```
ParticuleFastMatch.cpp  
#include <fstream>

Utilities.cpp
#include <random>
```

**Comment by jureviciusr** [comment]
Hi @patrickpoirier51 

I confirm the issue on my machine running Ubuntu 18.04 as well. I've fixed the includes and pushed the changes into master, thank you for reporting! Let me know if there are any other issues
