### ISSUE TITLE
Cuda Acceleration does not seems active

### ISSUE THREAD

**Issue by patrickpoirier51** [jureviciusr/particle-match#3]
Hello,

I enabled CUDA 
CMakeLists.txt
option(USE_OPENCV_CUDA= "Enable this flag to compile features requiring GPU support" ON)

ParticuleFastMatch.cpp
        //cv::Mat bestView = Utilities::extractWarpedMapPart(imageGray, templ.size(), transform);
        cv::cuda::GpuMat bestView = Utilities::extractWarpedMapPart(imageGrayGpu,

But it does not seem to use any GPU:

![image](https://user-images.githubusercontent.com/12484190/122457004-2e9f0580-cf7c-11eb-9933-e09a1d29e6af.png)

**Comment by jureviciusr** [comment]
Hi @patrickpoirier51 ,
I can see that process has allocated GPU memory, so it is running correctly. The GPU is used only for some operations -- not every part of the algorithm, so it's not expected to utilize a lot of GPU compute.

**Comment by patrickpoirier51** [comment]
Thanks for this very interesting demonstration and code @jureviciusr
